
spring:
  kafka:
    bootstrap-servers: "localhost:9092,localhost:9093,localhost:9094"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topics:
  people-basic:
    name: "people.basic.java"
    replicas: 3
    partitions: 3

management:
  endpoints:
    web:
      exposure:
        include: mappings
